language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- pytest --cov=./
before_install:
- openssl aes-256-cbc -K $encrypted_c7c730bf9b63_key -iv $encrypted_c7c730bf9b63_iv
  -in .travis/id_rsa.enc -out .travis/id_rsa -d
after_success:
- codecov --token=998994d9-6e62-44c2-81ee-4b7d79d9b479
- "./.travis/deploy.sh"
env:
  global:
    secure: FGcFAnDEI77wBXP3lzJVpP924QVW3ZX3UmuhKicVE7iWDGDA/TSeozwgj2+gCY48lDLUVj+4iY0rmVMWiePCJKIfVNk/5LnUsv4sUSas0gSvh2bHSyJhS/aYtg+2oKOL1bR285hxf3Z+SYDavVreL315FWep2dmTrkQBObJHYgVrrz2BGYcLiBqFV9Nuq+dDZeb+xvbq2QS6Fch7TMpCG9dmF4aKE/q2WVWIusJPnemGb9D0UH9wEu+2Ij+K70tkxGT4XEZQ1unYPtLtkYuDlZkiIYJayZ7lKvAoV9cBBAxjcO9pyv/lvyG+Oa5ZjPQkafyAcsK0pUFQp2bUvB4MpWXrqGq12XBy1dEQBcvTvwmf8HzdzazQh0CIhTPexi+bFkaXoHmnIpCVeKRKlOSSnQ3HtkrrMagz+8BfMcVH5reeaEvNGsR4XtYSaQllbZiKEXOggUxUbTkCHWdKdUVkraJ2nq43W5Mi5N+kNSbK57zhRWfqVZ1FhdPQJvjGvdwbENcEerO48TjJld8uM9OMqJ+XegP5Is98I7wX0rRMA2bshpD5U/YpyPR5vnb8KkHEQVGiMRa9fRvtEs5UyKqE0m9wjd9U83FEKK81SVmui/sPtRaNbRqJo+AWaO30ND8uJpXb6F1e1DoI4g2mfxV/oM1aMt/GM65kenJnKZ0zy0s=
